apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-crt
spec:
  secretName: tls-secret
  duration: 170000h
  renewBefore: 72h
  issuerRef:
    kind: Issuer
    name: selfsigned
  commonName: "mynodeapp.com"
  isCA: true
  dnsNames:
  - "mynodeapp.com"
